apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flaky-retry
spec:
  hosts:
  - flaky-service
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,connect-failure,refused-stream
    route:
    - destination:
        host: flaky-service
